name: Android CICD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Set up Node.js 13
        uses: actions/setup-node@v2
        with:
          node-version: '13'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Install NDK
        run: echo "y" | "${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager" --install "ndk;20.0.5594570"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build release
        run: ./gradlew assembleRelease

      - name: List files
        run: ls -lrt app/build/outputs/apk/release

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app/build/outputs/apk/release/app-release.apk
